package io.github.tanguygab.litebansexpansion;

public enum DataType {

    IS_BANNED,
    IS_TEMPBANNED,
    IS_MUTED,
    IS_TEMPMUTED,
    IS_WARNED,

    COUNT_BANS,
    COUNT_TEMPBANS,
    COUNT_MUTES,
    COUNT_TEMPMUTES,
    COUNT_KICKS,
    COUNT_WARNS,

    LAST_BAN_REASON,
    LAST_TEMPBAN_REASON,
    LAST_MUTE_REASON,
    LAST_TEMPMUTE_REASON,
    LAST_KICK_REASON,
    LAST_WARN_REASON,

    LAST_BAN_DATE,
    LAST_TEMPBAN_DATE,
    LAST_MUTE_DATE,
    LAST_TEMPMUTE_DATE,
    LAST_KICK_DATE,
    LAST_WARN_DATE,

    EXPIRY_TEMPBAN,
    EXPIRY_TEMPMUTE

}
